### ISSUE TITLE
ImportError: cannot import name 'Fitipy'

### ISSUE THREAD

**Issue by shipleyxie** [MatthewScholefield/fitipy#1]
File "/mycroft-precise-dev/precise/scripts/train.py", line 16, in <module>
    from fitipy import Fitipy
ImportError: cannot import name 'Fitipy'

Could you please tell me how to deal with this error?

**Comment by MatthewScholefield** [comment]
You need to install `fitipy<1.0`. You can do this with:
```
source .venv/bin/activate
pip install 'fitipy<1.0'
```
Note that the `./setup.sh` script in the mycroft precise repo should automatically do this.

Let me know if this helps,
Matthew

**Comment by shipleyxie** [comment]
use
`pip install fitipy==0.1.2`
can solve this question, but get another error 
> /mycroft-precise-dev/precise/scripts/train.py", line 19, in <module>
    from prettyparse import add_to_parser
ImportError: cannot import name 'add_to_parser'
solve thie by 
`pip install prettyparse==0.1.4`

The above error come out in WSL when installing Precise using ./setup.sh .

**Comment by MatthewScholefield** [comment]
If you happen to get a moment, can you post the output of running this in the venv?:

```bash
pip uninstall fitipy && pip install --upgrade "fitipy<1.0"

pip uninstall fitipy && pip install --upgrade "fitipy<1.0.0"
```
I'm curious if the versions are parsed differently on Python on your platform.

**Comment by shipleyxie** [comment]
> (.venv) shipley@LAPTOP-7EG23ELN:/mnt/d/Work/project/wuw/mycroft-precise-dev$ pip uninstall fitipy && pip install --upgrade "fitipy<1.0"
> Uninstalling fitipy-1.0.0:
>   Would remove:
>     /mnt/d/Work/project/wuw/mycroft-precise-dev/.venv/lib/python3.6/site-packages/fitipy-1.0.0.dist-info/*
>     /mnt/d/Work/project/wuw/mycroft-precise-dev/.venv/lib/python3.6/site-packages/fitipy.py
> Proceed (y/n)? y
>   Successfully uninstalled fitipy-1.0.0
> Processing /home/shipley/.cache/pip/wheels/bc/a8/ef/1566bd838229d39cf6501b33ee4d0bc4e1b12349540a9e5a75/fitipy-0.1.2-cp36-none-any.whl
> Installing collected packages: fitipy
> Successfully installed fitipy-0.1.2
> (.venv) shipley@LAPTOP-7EG23ELN:/mnt/d/Work/project/wuw/mycroft-precise-dev$ pip uninstall fitipy && pip install --upgrade "fitipy<1.0.0"
> Uninstalling fitipy-0.1.2:
>   Would remove:
>     /mnt/d/Work/project/wuw/mycroft-precise-dev/.venv/lib/python3.6/site-packages/fitipy-0.1.2.dist-info/*
>     /mnt/d/Work/project/wuw/mycroft-precise-dev/.venv/lib/python3.6/site-packages/fitipy.py
> Proceed (y/n)? y
>   Successfully uninstalled fitipy-0.1.2
> Processing /home/shipley/.cache/pip/wheels/bc/a8/ef/1566bd838229d39cf6501b33ee4d0bc4e1b12349540a9e5a75/fitipy-0.1.2-cp36-none-any.whl
> Installing collected packages: fitipy
> Successfully installed fitipy-0.1.2
> (.venv) shipley@LAPTOP-7EG23ELN:/mnt/d/Work/project/wuw/mycroft-precise-dev$

They produce the same result! Eh...the Error i meet are some kind of weird

**Comment by MatthewScholefield** [comment]
Thx for testing. Not sure what's wrong with `setup.sh` but I'm glad it's working now.
